# Site settings
title: "JavaScript Conference China 2017"
baseurl: ""
url: "http://2017.jsconf.cn"
exclude: ['README.md', 'package.json', 'bower.json', 'Gemfile', 'gulpfile.js', 'node_modules', 'dist/scss', 'dist/js', '*.log']
languages: ['cn', 'en']

collections:
  pastspeakers:
    output: false
  presentspeakers:
    output: false
  companies:
    output: false

# Plugins
gems:
  - jekyll-redirect-from
  - jekyll-paginate
  - jekyll-multiple-languages-plugin
